// <auto-generated />
namespace Design_Dashboard_Modern.MigracionC1
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MG11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MG11));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131505389_MG11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
