// <auto-generated />
namespace Design_Dashboard_Modern.MigracionC1
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MG6campoCuit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MG6campoCuit));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181938277_MG6-campoCuit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
